# This is a basic workflow to help you get started with Actions

name: Build and Tests

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [
        examples/BicyclePowerDisplay/BicyclePowerDisplay.ino,
        examples/BicyclePowerSensor/BicyclePowerSensor.ino,
        examples/BicycleSpeedDisplay/BicycleSpeedDisplay.ino,
        examples/DeviceSearch/DeviceSearch.ino,
        examples/DynamicProfiles/DynamicProfiles.ino,
        examples/EnvironmentDisplay/EnvironmentDisplay.ino,
        examples/HeartRateDisplay/HeartRateDisplay.ino,
        examples/HeartRateMonitor/HeartRateMonitor.ino,
        examples/LEVDisplay/LEVDisplay.ino,
        examples/MuscleOxygenMonitor/MuscleOxygenMonitor.ino,
        examples/ShiftingShifter/ShiftingShifter.ino]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Install library dependencies
        run: pio lib -g install ANT

      - name: Build example
        run: pio ci --board=teensy31 --lib="."
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}

  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v2
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Install platform
        run: pio platform install native

      - name: Install library dependencies
        run: pio lib -g install ANT

      - name: Run tests
        run: pio test -e native
